#!/usr/bin/env python

import sys

for line in sys.stdin:
    etiquetas = line.strip()
    etiqueta = etiquetas.split('\n')
    for etiqueta in etiquetas:
        if etiqueta != 'GENERO:':
            print '%s' % (etiqueta)
        if etiqueta == 'GENERO:':
            print '%s' % (etiqueta)
            break
