#!/usr/bin/env python

import sys
import os

try:
    input_file = os.environ['mapreduce_map_input_file']
except KeyError:
    input_file = os.environ['map_input_file']

fn = input_file.split(":")[-2:]

for line in sys.stdin:
    etiquetas = line.strip()
    words = etiquetas.split()
    for word in words:
        if word == 'AUTOR:':
            print '%s' % (fn)
